### ISSUE TITLE
Authenticated methods

### ISSUE THREAD

**Issue by AlessandroSpallina** [wmin0/node-cobinhood#3]
hey @wmin0, in this library authenticated methods over websocket are missing, have you planned to develop auth in these days?

**Comment by AlessandroSpallina** [comment]
anyway, i can't run the orderbook_ws.js example, i get 'subscribe' message but i don't receive any onmsg message.. any fix? thanks

**Comment by wmin0** [comment]
Hi @AlessandroSpallina, I checked why orderbook_ws.js don't work because of the precision is too old. I adjusted list pair flow and let you can get precision on demand. Please use correct precision and try it again.
Thanks.

**Comment by wmin0** [comment]
I found I answered an old question._.
Which auth method you need?
Trading related should have been provided.

**Comment by AlessandroSpallina** [comment]
For the first message: i deleted my message because i get answer from cobinhood just skipping "onOpen" line in orderbook_ws.js, just directly subscribing. Is this unsafe in your opinion?

For the second message: i need this one https://cobinhood.github.io/api-public/#order-auth
It's night here and my mind is not very fresh, but I'm pretty sure that in your library are missing trading features over websocket, i find them only in rest api version

**Comment by wmin0** [comment]
@AlessandroSpallina
1. Yeah, if you don't wait onopen, I cannot send message to server.
2. Okay, I put this feature less priority.
Because websocket will be disconnected every 3600s even I send ping/pong periodically, trading via websocket has chance losing some state.
If you really need it, I think I will develop in this two days.

**Comment by wmin0** [comment]
@AlessandroSpallina

plz try 0.2.3.
If you find problems, feel free to tell me :D

**Comment by AlessandroSpallina** [comment]
0.2.3 looks awesome :)
